/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContentRouteImport } from './routes/_content'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentStudyRouteImport } from './routes/_content/study'
import { Route as ContentQuizRouteImport } from './routes/_content/quiz'
import { Route as ContentListRouteImport } from './routes/_content/list'
import { Route as ContentDashboardRouteImport } from './routes/_content/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/_content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStudyRoute = ContentStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => ContentRoute,
} as any)
const ContentQuizRoute = ContentQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ContentRoute,
} as any)
const ContentListRoute = ContentListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ContentRoute,
} as any)
const ContentDashboardRoute = ContentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ContentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ContentDashboardRoute
  '/list': typeof ContentListRoute
  '/quiz': typeof ContentQuizRoute
  '/study': typeof ContentStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ContentDashboardRoute
  '/list': typeof ContentListRoute
  '/quiz': typeof ContentQuizRoute
  '/study': typeof ContentStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_content': typeof ContentRouteWithChildren
  '/login': typeof LoginRoute
  '/_content/dashboard': typeof ContentDashboardRoute
  '/_content/list': typeof ContentListRoute
  '/_content/quiz': typeof ContentQuizRoute
  '/_content/study': typeof ContentStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/list' | '/quiz' | '/study'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/list' | '/quiz' | '/study'
  id:
    | '__root__'
    | '/'
    | '/_content'
    | '/login'
    | '/_content/dashboard'
    | '/_content/list'
    | '/_content/quiz'
    | '/_content/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content': {
      id: '/_content'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content/study': {
      id: '/_content/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof ContentStudyRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/quiz': {
      id: '/_content/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof ContentQuizRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/list': {
      id: '/_content/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ContentListRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/dashboard': {
      id: '/_content/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ContentDashboardRouteImport
      parentRoute: typeof ContentRoute
    }
  }
}

interface ContentRouteChildren {
  ContentDashboardRoute: typeof ContentDashboardRoute
  ContentListRoute: typeof ContentListRoute
  ContentQuizRoute: typeof ContentQuizRoute
  ContentStudyRoute: typeof ContentStudyRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentDashboardRoute: ContentDashboardRoute,
  ContentListRoute: ContentListRoute,
  ContentQuizRoute: ContentQuizRoute,
  ContentStudyRoute: ContentStudyRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
